# Generated by Django 3.2.4 on 2021-06-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product_idx', models.IntegerField(db_column='PRODUCT_IDX', primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_column='USER_ID', max_length=30)),
                ('product_name', models.CharField(db_column='PRODUCT_NAME', max_length=30)),
                ('product_code', models.CharField(db_column='PRODUCT_CODE', max_length=30)),
                ('product_reg', models.DateField(db_column='PRODUCT_REG')),
                ('product_edit', models.DateField(db_column='PRODUCT_EDIT')),
                ('product_comment', models.CharField(blank=True, db_column='PRODUCT_COMMENT', max_length=500, null=True)),
                ('product_price', models.IntegerField(db_column='PRODUCT_PRICE')),
                ('product_res', models.CharField(blank=True, db_column='PRODUCT_RES', max_length=30, null=True)),
                ('product_state', models.CharField(db_column='PRODUCT_STATE', max_length=30)),
            ],
            options={
                'db_table': 'product_detail',
                'managed': False,
            },
        ),
    ]
